name = "MLDataStructs"
uuid = "231b2990-1215-4635-83e1-f406f0fcf969"
authors = ["joshday <emailjoshday@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
